version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: filp/whoops
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
    - 9.5.2
    - 9.5.3
  - dependency-name: mockery/mockery
    versions:
    - 1.3.4
  - dependency-name: nunomaduro/collision
    versions:
    - 3.1.0
  - dependency-name: laravel/framework
    versions:
    - 6.20.12
