name: CD-Staging

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run migrations via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: ${{ secrets.STAGING_SSH_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /home/dh_aiepbk/opemedios
            git checkout staging
            git pull origin staging
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
